name: Node.js package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Bump Version and Push Tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          WITH_V: true
          PRERELEASE_SUFFIX: dev

      - name: Build
        run: |
          tsc --project tsconfig.json --outDir .bin/esm --module ESNext
          tsc --project tsconfig.json --outDir .bin/node --module CommonJS
          node scripts/bump-version.mjs
        env:
          version: ${{ steps.bump_version.outputs.new_tag }}

      - name: Publish
        run: npm publish .bin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
